name: appacai
description: App de delivery de acai.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^0.4.0+5 # Recursos Básicos
  cloud_firestore: ^0.12.5 # Banco de Dados
  firebase_storage: ^3.0.1 # Armazenamento de Arquivos
  firebase_auth: ^0.11.1+6 # Autenticação de Usuários

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/acai.png
    - assets/images/acai_copo.png
    - assets/images/acai_tigela.png
